// src/components/Stepper/Stepper.vue
<template>
  <nav :data-testid="`${dataTestId}-navigation`" class="stepper">
    <Heading v-if="title" type="callout">
      {{ title }}
    </Heading>
    <ol :data-testid="`${dataTestId}-list`" class="steps">
      <li v-for="({ stepNumber, isActive, isInactive }) in availableSteps"
          :key="stepNumber"
          class="step"
          :class="{ active: isActive, inactive: isInactive }"
          :data-testid="`${dataTestId}-element`"
      >
        Paso {{ stepNumber }}
      </li>
    </ol>
  </nav>
</template>

<script src="./Stepper.js"/>
<style lang="scss" scoped src="./Stepper.scss"/>

// src/components/Stepper/Stepper.jsx
import { useMemo } from 'preact/hooks';
import PropTypes from 'prop-types';

import Heading from '../Heading/Heading';
import CSS from './styles.css';

const Stepper = ({ steps, activeStep, hideActive, title, className, dataTestId }) => useMemo(() => (
  <navigation data-testid={`${dataTestId}-navigation`} className={`${CSS.stepper} ${className}`}>
    {title && <Heading type="callout">{title}</Heading>}
    <ol data-testid={`${dataTestId}-list`} className={CSS.steps}>
      {[...Array(steps).keys()].map((step, index) => {
        const activeClass = ((index === activeStep) && !hideActive) ? CSS.active : '';
        const inactiveClass = (index > activeStep) ? CSS.inactive : '';
        return <li key={`${step}-${index}`} data-testid={`${dataTestId}-element`} className={`${CSS.step} ${activeClass} ${inactiveClass}`}>Paso {index + 1}</li>;
      })}
    </ol>
  </navigation>
), [steps, activeStep, hideActive]);

Stepper.defaultProps = {
  className: '',
  dataTestId: 'navigation-stepper',
  title: '',
  hideActive: false,
  activeStep: 0,
};

Stepper.propTypes = {
  steps: PropTypes.number.isRequired,
  activeStep: PropTypes.number,
  hideActive: PropTypes.bool,
  title: PropTypes.string,
  className: PropTypes.string,
  dataTestId: PropTypes.string,
};

export default Stepper;
