// src/components/ContentItem/ContentItem.vue
<template>
  <li class="item"
      :data-testid="dataTestId"
      :disabled="disabled"
      @click="emitClickEvent"
  >
    <div v-if="$slots.default"
         :data-testid="`${dataTestId}-media-icon`"
         class="media"
         :class="color"
    >
      <slot/>
    </div>
    <div :data-testid="`${dataTestId}-heading`" class="body">
      <Heading size="medium">{{ title }}</Heading>
      <TextParagraph v-if="metaText"
                     :data-test-id="`${dataTestId}-meta-text`"
      >
        {{ metaText }}
      </TextParagraph>
    </div>
    <ForwardIcon v-if="hasForwardButton"
                 class="forward-icon"
                 :data-testid="`${dataTestId}-forward-icon`"
    />
  </li>
</template>

<script src="./ContentItem.js"/>
<style lang="scss" scoped src="./ContentItem.scss"/>

// src/lists/ContentItem/index.jsx
import CSS from './styles.css'
import Heading from '../../typography/Heading'
import Text from '../../typography/Text'
import { ForwardIcon } from '@lana/b2c-mapp-ui-assets'

export default ({ mediaColor, media, meta, onClick, className, title, dataTestId }) => {
	const mediaColorClass = mediaColor ? CSS[mediaColor] : ''
	const mediaIcon = media ? <div className={`${CSS.media} ${mediaColorClass}`}>{media}</div> : ''
	const metaInfo = meta ? <Text>{meta}</Text> : ''
	const testId = dataTestId || 'content-item'

	return (
		<li
			data-testid={testId}
			onClick={onClick ? e => onClick(e) : false}
			className={`${CSS.item} ${className || ''}`}
		>
			{mediaIcon}
			<div data-testid={`${testId}-heading`} className={CSS.body}>
				<Heading type="txt-medium">{title}</Heading>
				{metaInfo}
			</div>
			{onClick ? (
				<ForwardIcon dataTestId={`${testId}-forward`} color="inactive" className={CSS.icon} />
			) : (
				''
			)}
		</li>
	)
}
