// src/buttons/FigureCard/index.jsx
import CSS from './styles.css'
import PropTypes from 'prop-types'
import Text from '../../typography/Text'

export default function FigureCard ({ dataTestId, size, className, meta, imageSrc, title }) {
	const backgroundStyle = {
		backgroundImage: `url('${imageSrc}')`,
	}

	return (
			<figure className={`${CSS.FigureCard} ${className} ${(size && CSS[size]) || ''}`}>
				<div className={CSS['image-wrapper']}>
					<div className={CSS['image']} data-testid={`${dataTestId}-image`} style={backgroundStyle} />
				</div>
				<figcaption>
					<Text dataTestId={`${dataTestId}-title`} type="txt-small">{title}</Text>
					{meta && <Text dataTestId={`${dataTestId}-meta`} type="txt-xsmall">{meta}</Text>}
				</figcaption>
			</figure>
	)
}

FigureCard.defaultProps = {
	dataTestId: 'figure-card',
	size: '',
	className: '',
	meta: '',
	title: '',
	imageSrc: ''
}

FigureCard.propTypes = {
	dataTestId: PropTypes.string,
	size: PropTypes.string,
	className: PropTypes.string,
	meta: PropTypes.string,
	title: PropTypes.string,
	imageSrc: PropTypes.string,
}

// src/components/FigureCard/FigureCard.vue
<template>
  <figure class="figure-card">
    <div class="image-wrapper">
      <div class="image"
           :data-testid="`${dataTestId}-image`"
           :style="backgroundStyle"
      />
    </div>
    <figcaption>
      <TextParagraph :data-test-id="`${dataTestId}-title`" size="small">{{ title }}</TextParagraph>
      <TextParagraph v-if="metaText"
                     :data-test-id="`${dataTestId}-meta`"
                     size="xsmall"
      >
        {{ metaText }}
      </TextParagraph>
    </figcaption>
  </figure>
</template>

<script src="./FigureCard.js"/>
<style lang="scss" scoped src="./FigureCard.scss"/>
