// src/components/FormField/FormField.vue
<template>
  <label :data-testid="`${dataTestId}-label`"
         class="field"
         :class="{ labeled: hasLabel, focus: isFocused, error: errorLabel, readonly }"
  >
    <slot/>
    <strong class="label">{{ errorLabelOrPlaceholder }}</strong>
    <input :id="inputId"
           ref="input"
           v-model="inputValue"
           :data-testid="`${dataTestId}-input`"
           :type="type"
           class="input"
           autocomplete="off"
           :name="name"
           :maxlength="maxLength"
           :readonly="readonly"
           :disabled="disabled"
           @focus="onFocus"
           @blur="onBlur"
    >
  </label>
</template>

<script src="./FormField.js"/>
<style lang="scss" scoped src="./FormField.scss"/>

// src/components/FormField/FormField.jsx
import { useMemo, useEffect, useRef } from 'preact/hooks';
import PropTypes from 'prop-types';

import { useToggle } from '../../utils/hooks';
import CSS from './styles.css';

const FormField = ({ id, name, dataTestId, errorLabel, startFocused, maxLength, type, value, readOnly, className, placeholder, showPrefix, children, onBlur, onChange, onFocus }) => {
  const [isFocused, toggleFocus] = useToggle(false);

  let inputRef = useRef(null);

  useEffect(() => {
    if (!startFocused) { return; }
    toggleFocus();
    if (inputRef) { inputRef.focus(); }
  }, []);

  const handleOnFocus = (event) => {
    toggleFocus();
    if (onFocus) { onFocus(event); }
  };

  const handleOnBlur = (event) => {
    toggleFocus();
    if (onBlur) { onBlur(event); }
  };

  const handleOnChange = ({ target: { value: fieldValue } }) => { if (onChange) { onChange(fieldValue); } };

  const result = (useMemo(() => {
    const isLabeled = (value !== '');
    const labeledClass = (showPrefix || isLabeled || readOnly) ? CSS.labeled : '';
    const inputId = (id !== null) ? id : name;
    return (
      <label
        data-testid={`${dataTestId}-label`}
        className={`${CSS.field} ${labeledClass} ${(isFocused) ? CSS.focus : ''} ${(errorLabel) ? CSS.error : ''} ${(readOnly) ? CSS.readonly : ''} ${className}`}
      >
        { children || '' }
        <strong className={CSS.label}>{errorLabel || placeholder}</strong>
        <input
          data-testid={`${dataTestId}-input`}
          id={inputId || name}
          ref={(element) => { inputRef = element; }}
          onFocus={handleOnFocus}
          onBlur={handleOnBlur}
          onChange={handleOnChange}
          onInput={handleOnChange}
          autoComplete="off"
          className={CSS.input}
          type={type}
          maxLength={maxLength}
          readOnly={readOnly}
          name={name}
          value={value}
        />
      </label>
    );
  }, [inputRef, isFocused, value]));
  return result;
};

FormField.defaultProps = {
  id: null,
  dataTestId: 'field',
  errorLabel: '',
  maxLength: 100,
  value: '',
  readOnly: false,
  className: '',
  showPrefix: false,
  children: null,
  startFocused: false,
  onBlur: null,
  onChange: null,
  onFocus: null,
};

FormField.propTypes = {
  name: PropTypes.string.isRequired,
  placeholder: PropTypes.string.isRequired,
  type: PropTypes.string.isRequired,
  errorLabel: PropTypes.string,
  id: PropTypes.string,
  dataTestId: PropTypes.string,
  maxLength: PropTypes.number,
  value: PropTypes.string,
  readOnly: PropTypes.bool,
  startFocused: PropTypes.bool,
  className: PropTypes.string,
  showPrefix: PropTypes.bool,
  children: PropTypes.node,
  onBlur: PropTypes.func,
  onChange: PropTypes.func,
  onFocus: PropTypes.func,
};

export default FormField;
