// src/components/ActionItem/ActionItem.vue
<template>
  <li :data-testid="dataTestId"
      class="item"
      @click="onClick"
  >
    <div v-if="$slots.default"
         class="media"
         :data-testid="`${dataTestId}-mediacolor`"
    >
      <slot/>
    </div>
    <div class="body">
      <TextParagraph class="title"
                     :class="{ highlight }"
                     :data-testid="`${dataTestId}-highlight`"
      >
        {{ title }}
      </TextParagraph>
    </div>
  </li>
</template>

<script src="./ActionItem.js"/>
<style lang="scss" scoped src="./ActionItem.scss"/>

// src/lists/ActionItem/ActionItem.jsx
import CSS from './ActionItem.css'
import Text from '../../typography/Text'

export default ({ onClick, media, mediaColor, highlight, className, title }) => {
	const mediaColorClass = (mediaColor) ? CSS[mediaColor] : ''
	const highLighClass = highlight ? `${CSS['highlight']}` : ''
	return (
		<li onClick={(onClick) ? e => onClick(e) : false} className={`${CSS.item} ${className || ''}`}>
			{media && <div className={`${CSS.media} ${mediaColorClass}`}>{media}</div>}
			<div className={CSS.body}>
				<Text className={highLighClass}>{title}</Text>
			</div>
		</li>
	)
}
