// src/components/ActionItem/ActionItem.vue
<template>
  <li :data-testid="dataTestId"
      class="item"
      @click="onClick"
  >
    <div v-if="$slots.default"
         class="media"
         :data-testid="`${dataTestId}-mediacolor`"
    >
      <slot/>
    </div>
    <div class="body">
      <TextParagraph class="title"
                     :class="{ highlight }"
                     :data-testid="`${dataTestId}-highlight`"
      >
        {{ title }}
      </TextParagraph>
    </div>
  </li>
</template>

<script src="./ActionItem.js"/>
<style lang="scss" scoped src="./ActionItem.scss"/>

// src/lists/ActionItem/index.jsx
import PropTypes from 'prop-types';

import CSS from './styles.css'
import Text from '../../typography/Text'

const ActionItem = ({ onClick, mediaContent, mediaColor, highlight, className, title, dataTestId }) => {
	const mediaColorClass = (mediaColor) ? CSS[mediaColor] : '';
	const highLighClass = (highlight) ? `${CSS['highlight']}` : '';

	return (
		<li data-testid={dataTestId} onClick={(onClick) ? e => onClick(e) : false} className={`${CSS.item} ${className}`}>
			{mediaContent && <div data-testid={`${dataTestId}-mediacolor`} className={`${CSS.media} ${mediaColorClass}`}>{mediaContent}</div>}
			<div className={CSS.body}>
				<Text dataTestId={`${dataTestId}-highlight`} className={highLighClass}>{title}</Text>
			</div>
		</li>
	)
}

ActionItem.defaultProps = {
	dataTestId: 'action-item',
	className: '',
	onClick: null,
	mediaContent: null,
	mediaColor: false,
	highlight: false,
}

ActionItem.propTypes = {
	onClick: PropTypes.func,
	mediaContent: PropTypes.node,
	mediaColor: PropTypes.bool,
	highlight: PropTypes.bool,
	dataTestId: PropTypes.string,
	className: PropTypes.string,
	title: PropTypes.string.isRequired
}

export default ActionItem;
